### ISSUE TITLE
Add new block: Form

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#10]
**Block: Form** 
Form block is a wrapper for any other blocks, and may handle user input.

```yaml
- type: Form
  properties:
    id: # Form ID 
    name: # Form name
    method: # Form method, post or get, default is post
    class: # Form class
    style: # Form style array
    data: # Form data array
    events: # Form events array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
