### ISSUE TITLE
Add new block: Heading

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#11]
**Block: Heading** 
Creates a Heading.

```yaml
- type: Heading
  properties:
    size: # Heading size (huge, large, medium, small, tiny) default is medium
    id: # Heading ID
    class: # Heading class
    style: # Heading style array
    data: # Heading data array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
