### ISSUE TITLE
Add new block: Image

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#12]
**Block: Image** 
Creates Image.

```yaml
- type: Image
  properties:
    id: # Image ID
    src: # Image src
    alt: # Image alt
    width: # Image width
    height: # Image height
    loading: # Image loading 
    class: # Image class
    style: # Image style array
    data: # Image data array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
