### ISSUE TITLE
Add new block: InputButton

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#13]
**Block: InputButton** 

```yaml
- type: InputButton
  properties:
    id: # InputButton ID
    name: # InputButton name
    title: # InputButton value
    class: # InputButton class
    style: # InputButton style array
    data: # InputButton data array
    disabled: # InputButton disabled or not default is false
    events: # InputButton events array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
