### ISSUE TITLE
Add new block: InputEmail

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#14]
**Block: InputEmail** 

```yaml
- type: InputEmail
  properties:
    id: # InputEmail ID
    name: # InputEmail name
    label:
      title: # InputEmail label title
      class: # InputEmail label class
      style: # InputEmail label style array
    class: # InputEmail class
    style: # InputEmail style array
    data: # InputEmail data array
    disabled: # InputEmail disabled or not default is false
    events: # InputEmail events array
    placeholder: # InputEmail placeholder
    readonly: # InputEmail readonly set `true` or `false`
    disabled: # InputEmail disabled set `true` or `false`
    value: # InputEmail value
    validation: # InputEmail 
      maxlength: # Specifies the maximum length of textual data (strings)
      minlength: # Specifies the minimum length of textual data (strings)
      required: # Specifies whether a form field needs to be filled in before the form can be submitted.
      pattern:  # Specifies a regular expression that defines a pattern the entered data needs to follow.
      errorMessage: # Specifies error message
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
