### ISSUE TITLE
Add new block: InputHidden

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#15]
**Block: InputHidden** 

```yaml
- type: InputHidden
  properties:
    id: # InputHidden ID
    name: # InputHidden name
    value: # InputHidden value
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
