### ISSUE TITLE
Add new block: InputNumber

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#16]
**Block: InputNumber** 

```yaml
- type: InputNumber
  properties:
    id: # InputNumber ID
    name: # InputNumber name
    label:
      title: # InputNumber label title
      class: # InputNumber label class
      style: # InputNumber label style array
    class: # InputNumber class
    style: # InputNumber style array
    data: # InputNumber data array
    disabled: # InputNumber disabled or not default is false
    events: # InputNumber events array
    placeholder: # InputNumber placeholder
    readonly: # InputNumber readonly set `true` or `false`
    disabled: # InputNumber disabled set `true` or `false`
    min: # InputNumber minimum number
    max: # InputNumber maximum number
    step: # InputNumber step number
    value: # InputNumber value
    validation: # InputNumber 
      max: # Specifies the maximum values of numerical input types
      min: # Specifies the minimum values of numerical input types
      required: # Specifies whether a form field needs to be filled in before the form can be submitted.
      pattern:  # Specifies a regular expression that defines a pattern the entered data needs to follow.
      errorMessage: # Specifies error message
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
