### ISSUE TITLE
Add new block: InputPassword

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#17]
**Block: InputPassword** 

```yaml
- type: InputPassword
  properties:
    id: # InputPassword ID
    name: # InputPassword name
    label:
      title: # InputPassword label title
      class: # InputPassword label class
      style: # InputPassword label style array
    class: # InputPassword class
    style: # InputPassword style array
    data: # InputPassword data array
    disabled: # InputPassword disabled or not default is false
    events: # InputPassword events array
    placeholder: # InputPassword placeholder
    readonly: # InputPassword readonly set `true` or `false`
    disabled: # InputPassword disabled set `true` or `false`
    value: # InputPassword value
    validation: # InputPassword 
      maxlength: # Specifies the maximum length of textual data (strings)
      minlength: # Specifies the minimum length of textual data (strings)
      required: # Specifies whether a form field needs to be filled in before the form can be submitted.
      pattern:  # Specifies a regular expression that defines a pattern the entered data needs to follow.
      errorMessage: # Specifies error message
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
