### ISSUE TITLE
Add new block: InputSelect

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#18]
**Block: InputSelect** 

```yaml
- type: InputSelect
  properties:
    id: # InputSelect ID
    name: # InputSelect name
    label:
      title: # InputSelect label title
      class: # InputSelect label class
      style: # InputSelect label style array
    class: # InputSelect class
    style: # InputSelect style array
    data: # InputSelect data array
    items: # InputSelect items array or items json string
    disabled: # InputSelect disabled or not default is false
    events: # InputSelect events array
    placeholder: # InputSelect placeholder
    disabled: # InputSelect disabled set `true` or `false`
    value: # InputSelect value
    validation: # InputSelect 
      required: # Specifies whether a form field needs to be filled in before the form can be submitted.
      errorMessage: # Specifies error message
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
