### ISSUE TITLE
Add new block: Tabs

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#19]
**Block: Tabs** 

```yaml
- type: Tabs
  properties:
    id: # Tabs ID
    class: # Tabs class
    style: # Tabs style array
    data: # Tabs data array
    tabs: # Tabs items with title and nested blocks
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
