### ISSUE TITLE
Add new block: Anchor

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#2]
**Block: Anchor** 
Creates a clickable text.

```yaml
- type: Anchor
  properties:
    id: # Anchor ID 
    title: # Anchor title
    href: # Anchor href
    class: # Anchor class
    style: # Anchor style array
    data: # Anchor data array
    events: # Anchor events array
    target: # Anchor target
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
