### ISSUE TITLE
Add new block: InputText

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#22]
**Block: InputText** 

```yaml
- type: InputText
  properties:
    id: # InputText ID
    name: # InputText name
    label:
      value: # InputText label title
      class: # InputText label class
      style: # InputText label style array
    class: # InputText class
    style: # InputText style array
    data: # InputText data array
    disabled: # InputText disabled or not default is false
    events: # InputText events array
    placeholder: # InputText placeholder
    readonly: # InputText readonly set `true` or `false`
    disabled: # InputText disabled set `true` or `false`
    value: # InputText value
    validation: # InputText 
      maxlength: # Specifies the maximum length of textual data (strings)
      minlength: # Specifies the minimum length of textual data (strings)
      required: # Specifies whether a form field needs to be filled in before the form can be submitted.
      pattern:  # Specifies a regular expression that defines a pattern the entered data needs to follow.
      errorMessage: # Specifies error message
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
