### ISSUE TITLE
Add ability to create blueprint vars

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#24]
We should able to create vars for current blueprint

Example:
```yaml
vars:
  foo: bar
  zed: zzz
```

Epic: #1
