### ISSUE TITLE
Add forms processing 

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#25]
We should have general forms process functionality to simplify and standardize forms handling on the backend. 

YAML structure (example):
```yaml
blocks:
  - type: Form
    process:
      actions:
        - name: createPostOnTwitter
          properties:
            fields: __self.fields
        - name: createPostOnFacebook
          properties:
            fields: __self.fields
      fields:
        - name: title
          type: string
        - name: content
          type: string
        - name: description
          type: string
        - name: routable
          type: bool
        - name: visibility
          type: string
        - name: published_at
          type: string
        - name: publised_by
          type: string
          value: "{{ flextype.acl.getUserLoggedInUuid() }}"
        - name: template 
          type: string
        - name: menu_item_title
          type: string
        - name: menu_item_url
          type: string
        - name: menu_item_target
          type: string
        - name: menu_item_order
          type: int
      messages: 
        error: "{{ __('admin_message_entry_changes_not_saved') }}"               
        success: "{{ __('admin_message_entry_changes_saved') }}"
      redirect:
        route: admin.entries.edit 
        args:
          id: id
          editor: editor
          blueprint: blueprint
          action: action
    properties: 
      name: form_entries_edit
    blocks:
      ...
        ...
          ...
```

PHP handling (example):
```php
$form = flextype('blueprints')->form($request->getParsedBody());
$form->getActions();

if (flextype('entries')->create($id, $form->getFields())) {
    flextype('flash')->addMessages('success', $form->getMessage('success'));
} else {
    flextype('flash')->addMessages('error', $form->getMessage('error'));
}

return $response->withRedirect($form->getRedirect(['id' => $id, 'type' => $type]));
```

Epic: #1
