### ISSUE TITLE
Add new block: Alert 

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#3]
**Block: Alert** 
Provide contextual feedback messages for typical user actions with the handful of available and flexible alert messages.

```yaml
- type: Alert
  properties:
    id: # Alert ID
    header:
      title: # Alert header title
      class: # Alert header class
      style: # Alert header style array
      data: # Alert header data array
    message: # Alert message
    class: # Alert class
    style: # Alert style array
    data: # Alert data array
    type: # Alert type (primary, secondary, success, info, warning, danger)
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
