### ISSUE TITLE
Add new block: Button

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#4]
**Block: Button** 
Render button.

```yaml
- type: Button
  properties:
    id: # Button ID
    title: # Button title
    class: # Button class
    style: # Button style array
    data: # Button data array
    events: # Button events array
    size: # Button size (large, small)
    type: # Button type (primary, secondary, success, info, warning, danger, link)
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
