### ISSUE TITLE
Add new block: ButtonGroup

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#5]
**Block: ButtonGroup** 
Render group of buttons together on a single line or stack them in a vertical column.

```yaml
- type: ButtonGroup
  properties: 
    id: # ButtonGroup ID
    title: # ButtonGroup title
    class: # ButtonGroup class
    style: # ButtonGroup style array
    data: # ButtonGroup data array
    events: # ButtonGroup events array
    size: # ButtonGroup size (large, small)
    vertical: # ButtonGroup vertical (set: true)
    buttons:
      - type: Button 
        properties:
          id: # Button ID
          title: # Button title
          class: # Button class
          style: # Button style array
          data: # Button data array
          events: # Button events array
          type: # Button type (primary, secondary, success, info, warning, danger, link)
          icon:
            name: # Icon name
            set: # Icon set
      - type: ButtonToggle
        properties:
          id: # Button ID
          title: # Button title
          class: # Button class
          style: # Button style array
          data: # Button data array
          events: # Button events array
          type: # Button type (primary, secondary, success, info, warning, danger, link)
          icon:
            name: # Icon name
            set: # Icon set
          toogle:
            class: # Button toogle class
            style: # Button toogle style array
            data: # Button toogle data array
          items:
            id: # Item ID
            title: # Item title
            class: # Item class
            style: # Item style array
            data: # Item data array
            href: # Item href
            icon:
              name: # Icon name
              set: # Icon set
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
