### ISSUE TITLE
Add new block: Row

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#7]
**Block: Row** 
Row block is a wrapper for any other blocks.

```yaml
- type: Row
  properties:
    class: # Row class
    style: # Row style array
    data: # Row data array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
