### ISSUE TITLE
Add new block: Container

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#8]
**Block: Container** 
Container block is a wrapper for any other blocks.

```yaml
- type: Container
  properties:
    breakpoint: # Container breakpoint (extra small, small, medium, large, extra large, extra extra large, fluid)
    class: # Container class
    style: # Container style array
    data: # Container data array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
