### ISSUE TITLE
Add new block: Divider

### ISSUE THREAD

**Issue by Awilum** [flextype-plugins/blueprints#9]
**Block: Divider** 
Draws a horizontal line

```yaml
- type: Divider
  properties:
    dashed: # Divider dashed, set true or false (default)
    class: # Divider class
    style: # Divider style array
    data: # Divider data array
```

Epic: https://github.com/flextype-plugins/blueprints/issues/1
